changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot[bot]

  categories:
    - title: Bug fixes 🐛
      labels:
        - fixes
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: New Features 🎉
      labels:
        - features
    - title: Experimental 🧪
      labels:
        - experimental
    - title: Contributions
      labels:
        - "*"
