changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot[bot]

  categories:
    - title: 🐞 Bug Fixes
      labels:
        - fixes
    - title: ⚠️ Breaking Changes
      labels:
        - breaking
    - title: 🚀 Features
      labels:
        - features
    - title: 🚧 Experimental
      labels:
        - experimental
    - title: 📝 Notable Changes
      labels:
        - "*"
